[tool.poetry]
name = "opspilot"
version = "0.1.0"
description = ""
authors = ["Chadrack MAYAMBA"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
pydantic = "^2.13.5"
chromadb = "^1.5.9"
langgraph = "^1.2.14"
langchain-google-genai = "^4.4.0"
fastapi = "^0.142.3"
streamlit = "^1.65.0"
requests = "^2.34.2"


[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
